---
- name: Retrieve main database password
  shell: docker exec -it  "{{ wp_host }}" env  | grep WORDPRESS_DB_PASS | awk -F "=" '{print $2}'
  register: db_password

- name: Create Nginx directory
  file:
    path: "/srv/www/{{ domain }}/nginx"
    state: directory

- name: Create Nginx directory
  file:
    path: "/srv/www/{{ domain }}/nginx/my-admin"
    state: directory

- name: Create SSL directory
  file:
    path: /srv/ssl
    state: directory

- name: Strip subdomain
  shell: echo {{ domain }} | sed 's/.*\.\(.*\..*\)/\1/'
  register: strip_domain

- name: Deploy Nginx configuration file
  template:
    src: index.html
    dest: "/srv/www/{{ domain }}/nginx/my-admin/index.html"

- name: Deploy global configuration files
  template:
    src: "{{ item }}"
    dest: "/srv/www/{{ domain }}/nginx/{{ item }}"
  with_items:
    - php.conf
    - nginx.conf
    - default.conf
    - fastcgi.conf

- name: Enable vouch SSO
  template:
    src: vouch.conf
    dest: "/srv/www/{{ domain }}/nginx/vouch.conf"

- name: Deploy global configuration files
  template:
    src: "{{ item }}"
    dest: "/srv/www/{{ domain }}/nginx/{{ item }}"
  with_items:
    - default.conf

- name: Check if rnd exists
  stat:
    path: /root/.rnd
  register: ssl_enabled

- name: Generate rnd
  command: dd if=/dev/urandom of=/root/.rnd bs=256 count=1
  when: ssl_enabled.stat.exists == False

- name: Create self-signed certificate, if configured.
  command: >
    openssl req -x509 -nodes -subj '/CN={{ inventory_hostname }}' -days 365
    -newkey rsa:2048 -sha256 -keyout "/srv/ssl/server.key" -out "/srv/ssl/server.crt"
    creates="/srv/ssl/server.crt"
  when: ssl_enabled.stat.exists == False

- name: Retrieve database password
  shell: "docker exec -it  {{ db_user }}_mysql env  | grep MARIADB_PASSWORD | awk -F '=' '{print $2}'"
  register: db_pass

- name: Create http basic authentication users
  htpasswd:
    path: "/srv/www/{{ domain }}/nginx/.htpasswd"
    name: "{{ db_user }}"
    password: "{{ db_pass.stdout }}"
    owner: 33
    group: 33
    mode: 0640

- name: Start phpmyadmin
  docker_container:
    env:
      PMA_HOST: "{{ db_host }}"
      PMA_USER: "{{ db_user }}"
      PMA_PASSWORD: "{{ db_password.stdout }}"
    name: "pma_{{ db_user }}"
    image: phpmyadmin/phpmyadmin
    restart: yes
    networks:
      - name: admin
      - name: "{{ wp_host }}"

- name: Start Nginx container
  docker_container:
    env:
      HTTPS_METHOD: "{{ https_method | default ('redirect') }}"
      VIRTUAL_HOST: "{{ domain }},www.{{ domain }}"
      LETSENCRYPT_HOST: "{{ domain }},www.{{ domain }}"
      LETSENCRYPT_EMAIL: "{{ letsencrypt_email }}"
    name: "{{ db_user }}_nginx"
    image: "{{ nginx_image }}"
    restart: yes
    restart_policy: always
    networks_cli_compatible: yes
    networks:
      - name: "{{ wp_network }}"
      - name: nginx_proxy
      - name: "vouch_{{ wp_network }}"
    volumes:
      - nginx_cache:/tmp/fastcgi_cache
      - "/srv/www/{{ domain }}/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf"
      - "/srv/www/{{ domain }}/www_data:/var/www/html:rw"
      - "/srv/www/{{ domain }}/nginx/php.conf:/etc/nginx/php.conf:ro"
      - "/srv/www/{{ domain }}/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "/srv/www/{{ domain }}/nginx/vouch.conf:/etc/nginx/vouch.conf"
      - "/srv/www/{{ domain }}/nginx/my-admin:/var/www/html/my-admin"
      - "/srv/www/{{ domain }}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "/var/log/nginx/{{ domain }}:/var/log/nginx"
      - "/srv/ssl:/etc/nginx/ssl:ro"
      - "/srv/www/{{ domain }}/nginx/.htpasswd:/etc/nginx/.htpasswd"
