---
- name: Deploy global configuration files
  template:
    src: "{{ item }}"
    dest: "/srv/www/{{ domain }}/nginx/{{ item }}"
  with_items:
    - default.conf

- name: Create Nginx directory
  file:
    path: "/srv/ssl"
    state: directory

- name: Generate random file
  command: dd if=/dev/urandom of=/root/.rnd bs=256 count=1

- name: Create self-signed certificate, if configured.
  command: >
    openssl req -x509 -nodes -subj '/CN={{ inventory_hostname }}' -days 365
    -newkey rsa:2048 -sha256 -keyout "/srv/ssl/server.key" -out "/srv/ssl/server.crt"
    creates="/srv/ssl/server.crt"
    
- name: Create htpasswd directory
  file:
    path: "/srv/www/{{ domain }}/nginx/{{ item }}"
    state: directory
  with_items:
    - htpasswd

- name: Create http basic authentication users
  htpasswd:
    path: "/srv/www/{{ domain }}/nginx/htpasswd/{{ item }}"
    name: "{{ db_user }}"
    password: "{{ db_pass }}"
    owner: systemd-resolve
    group: systemd-journal
    mode: 0640
  with_items:
    - "{{ domain }}"
    - "www.{{ domain }}"

- name: Start Nginx container (no extrax)
  docker_container:
    env:
      HTTPS_METHOD: "{{ https_method }}"
      VIRTUAL_HOST: "{{ domain }},www.{{ domain }},mysql.{{ domain }},logs.{{ domain }},webftp.{{ domain }}"
      LETSENCRYPT_HOST: "{{ domain }},www.{{ domain }},mysql.{{ domain }},logs.{{ domain }},webftp.{{ domain }}"
      LETSENCRYPT_EMAIL: "{{ letsencrypt_email }}"
    name: "nginx_{{ db_user }}"
    image: "{{ nginx_image }}"
    restart: yes
    restart_policy: always
    networks_cli_compatible: yes
    networks:
      - name: "{{ wp_network }}"
      - name: nginx_proxy
    volumes:
      - nginx_cache:/tmp/fastcgi_cache
      - "/srv/www/{{ domain }}/www_data:/var/www/html:rw"
      - "/srv/www/{{ domain }}/nginx/php.conf:/etc/nginx/php.conf:ro"
      - "/srv/www/{{ domain }}/nginx/vouch.conf:/etc/nginx/vouch.conf:ro"
      - "/srv/www/{{ domain }}/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "/srv/www/{{ domain }}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "/var/log/nginx/{{ domain }}:/var/log/nginx"
      - "/srv/ssl:/etc/nginx/ssl:ro"
      - "/srv/www/{{ domain }}/nginx/.htpasswd:/etc/nginx/.htpasswd"
  when: debug is not defined and full is not defined

- name: Start Nginx container in debug mode
  docker_container:
    name: "nginx_{{ db_user }}"
    image: nginx:alpine
    restart: yes
    restart_policy: always
    networks_cli_compatible: yes
    networks:
      - name: "{{ wp_network }}"
      - name: vouch
      - name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - nginx_cache:/tmp/fastcgi_cache
      - "/srv/www/{{ domain }}/www_data:/var/www/html:rw"
      - "/srv/www/{{ domain }}/nginx/php.conf:/etc/nginx/php.conf:ro"
      - "/srv/www/{{ domain }}/nginx/vouch.conf:/etc/nginx/vouch.conf:ro"
      - "/srv/www/{{ domain }}/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "/srv/www/{{ domain }}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "/srv/www/{{ domain }}/nginx/.htpasswd:/etc/nginx/.htpasswd"
  when: debug is defined
